###
post http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "test1",
    "name": "test1",
    "password": "test1",
    "role": "admin"
}

###
post http://localhost:3000/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}
